# Generated by Django 5.0.4 on 2024-06-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrera',
            field=models.CharField(default='ing civil', max_length=50),
            preserve_default=False,
        ),
    ]
