# Generated by Django 5.0.4 on 2024-06-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0003_remove_eval_prueba'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='evaluations',
            field=models.ManyToManyField(blank=True, related_name='users', to='evaluation.eval'),
        ),
    ]
