# Generated by Django 5.0.4 on 2024-06-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_evaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='evaluations',
        ),
    ]
